### ISSUE TITLE
Compilation fails because of use of gtest (googletest) test library

### ISSUE THREAD

**Issue by rpgoldman** [ths-rwth/smtrat#106]
After fixing issue #105 in [my fork of smtrat](https://github.com/rpgoldman/smtrat) I was able to get through the compilation errors pertaining to `RealAlgebraicNumber`.  However, now there were troubles with an undefined header from `gtest`.

I fixed that problem by adding googletest to the cmake resources.  See [this commit](https://github.com/rpgoldman/smtrat/commit/3aa41e8a8144653b8598ec908ebed89545972471).

This gets us much further, but still fails in compilation with this error:

```
Scanning dependencies of target runCadcellsTest
make[2]: *** No rule to make target 'resources/src/CArL-EP-build/resources/src/GTest-EP-build/googlemock/gtest/libgtest.a', needed by 'runCadcellsTest'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 44%] Building CXX object src/tests/smtrat-cadcells/CMakeFiles/runCadcellsTest.dir/datastructures_polynomials.cpp.o
[ 44%] Building CXX object src/cli/CMakeFiles/smtrat-objects.dir/parser/ParserWrapper.cpp.o
make[1]: *** [CMakeFiles/Makefile2:28615: src/tests/smtrat-cadcells/CMakeFiles/runCadcellsTest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

This error can be seen in a [GitHub Action transcript](https://github.com/rpgoldman/smtrat/actions/runs/3413743012/jobs/5680820057).

I suspect that my attempt failed because I needed to not just install gtest, but also build it. However, that was more than I knew how to do.  Is it possible to simply remove the tests from the build script?

**Comment by derjasper** [comment]
Fixed in the new release (which is there now!)
