### ISSUE TITLE
Have model that seems to parse successfully but hangs in preprocessing

### ISSUE THREAD

**Issue by rpgoldman** [ths-rwth/smtrat#108]
I do this and `smtrat-shared` hangs for more than 10 minutes:

    smtrat-shared --preprocess --pp-output-file preprocessed.smt2 chime_flat_20_for_smtrat.smt2

[chime_flat_20_for_smtrat.smt2.txt](https://github.com/ths-rwth/smtrat/files/10036532/chime_flat_20_for_smtrat.smt2.txt)

My guess is that SMT-RAT is translating the reals in the model into rationals, and  the reals in the model cause an explosion.  This is a model extracted from a simulator based on the SIR model for epidemiology, and the indices (20, 10) specify how many time steps we are considering. The explosion may come from the `beta` constant which is approximately O(10^-5).

To illustrate this, I show a much smaller model and the output of the preprocessor for that model.

[chime_flat_10_for_smtrat.smt2.txt](https://github.com/ths-rwth/smtrat/files/10036535/chime_flat_10_for_smtrat.smt2.txt)
[preprocessed.smt2.txt](https://github.com/ths-rwth/smtrat/files/10036536/preprocessed.smt2.txt)

This is with `smtrat-shared` as compiled normally. When I ask for the strategy I see this:
```
$ smtrat-shared --strategy
Module (24)
    FPPModule<FPPSettings1> (7)
        IncWidthModule<IncWidthSettings1> (6)
            IntBlastModule<IntBlastSettings2> (5)
                SATModule<SATSettings1> (4)
                    LRAModule<LRASettings1> (3)
                        VSModule<VSSettings234> (2)
                            NewCoveringModule<NewCovering> (1)
                                NewCADModule<NewCADFO> (0)
    FPPModule<FPPSettings1> (14)
        SATModule<SATSettings1> (13)
            STropModule<STropSettings1> (12)
                ICPModule<ICPSettings1> (11)
                    VSModule<VSSettings234> (10)
                        NewCoveringModule<NewCovering> (9)
                            NewCADModule<NewCADFO> (8)
    FPPModule<FPPSettings1> (20)
        SATModule<SATSettings1> (17)
            CubeLIAModule<CubeLIASettings1> (16)
                LRAModule<LRASettings1> (15)
        SATModule<SATSettings1> (19)
            LRAModule<LRASettings1> (18)
    FPPModule<FPPSettings1> (23)
        SATModule<SATSettings1> (22)
            LRAModule<LRASettings1> (21)

Could not open file:
```

I'm afraid I'm not sure how to read the above, since I don't know what the various `Settings` are or where to find them.

I see that the default strategy seems to be "SMTCOMP", but the documentation is only drawn from the code and I couldn't find a description of what it is expected to do from that.  But maybe I have missed something? All I could find was some doxygen documents [here](https://ths-rwth.github.io/smtrat/d2/de6/classsmtrat_1_1SMTCOMP.html)

In the doxygen docs, the "Detailed Description" everywhere I checked was just the place holder "Strategy Description"

**Comment by derjasper** [comment]
Thanks for bringing that up! Indeed, our preprocessing causes blow up on coefficients in some cases. I am having a quick look on that.

**Comment by rpgoldman** [comment]
@derjasper Is there anything in an article or web post that describes how SMT-RAT handles floating point?

Do you always transform floats to rationals?  Thanks!

**Comment by derjasper** [comment]
We do not support floating point arithmetic. So smtrat should throw an error of there is any floating point variable in the input.

Am 18. November 2022 16:53:14 MEZ schrieb rpgoldman ***@***.***>:
***@***.*** Is there anything in an article or web post that describes how SMT-RAT handles floating point?

**Comment by rpgoldman** [comment]
@derjasper It looks like the parser (or the preprocessor?) is translating floating point constants into rationals (ratios of integers). Is it possible that the parser is removing the floating point constants before they get to SMT-RAT and throw an error?

A colleague of mine has been successfully solving these models using dreal, which does use floating point arithmetic, and failing with Z3, which I believe does not.

**Comment by rpgoldman** [comment]
@derjasper Note that since this is effectively a discretized set of ODEs, there is discrete approximation of integration, which I think causes the rationals to get larger in representation size as the models get larger.

Are there encoding tricks commonly used for situations like this? This seems like it might be a common case

**Comment by derjasper** [comment]
I just released a new version of SMT-RAT that addresses this issue at least to some degree. 
I am sorry for the late release, there were several deadlines in between.

**Comment by rpgoldman** [comment]
@derjasper Thank you very much! This release is indeed a *huge* improvement.  I'm going to close this issue.
