### ISSUE TITLE
--preprocess option no longer supported?

### ISSUE THREAD

**Issue by rpgoldman** [ths-rwth/smtrat#111]
I tried to use the `--preprocess` and `--pp-output-file` options to `smtrat-shared` after a new build and got the following error:

    ERROR smtrat: This version of SMT-RAT was compiled without support for stand-alone preprocessing.

Was this change intended?  It's problematic because it makes it much harder to investigate issues such as #108

**Comment by rpgoldman** [comment]
Looks like I need to do the following now:

    cmake -DCLI_ENABLE_PREPROCESSOR=ON ..

I urge you to restore the `ON` setting as a default -- it's very useful and the default being `OFF` can be quite confusing since the relevant flags are *not* dropped from the `--help` output.

**Comment by derjasper** [comment]
We will add some hints to the cmake options.
