### ISSUE TITLE
Bug: Solver crashes on optimization problem

### ISSUE THREAD

**Issue by bruderj15** [ths-rwth/smtrat#112]
Hello there.

I recently stumbled upon this solver.
However I could not get my first optimization example running.
Below the input-file `in.smt2`:

```smt2
(set-option :produce-models true)
(set-logic QF_LIA)

(declare-fun var_1 () Int)
(assert (> var_1 0))
(minimize var_1)

(check-sat)
(get-model)
```
Solver answers with:
```bash
terminate called after throwing an instance of 'std::bad_variant_access'
  what():  std::get: wrong index for variant
/opt/smtrat/smtrat: line 3:  8962 Aborted                 (core dumped) LD_PRELOAD=$SCRIPTDIR/libmimalloc.so $SCRIPTDIR/smtrat-static $1
```

Ran on Linux with v24.06 from the binary release in this repo, with command-line: `smtrat in.smt2`

Removing the optimization instruction `(minimize var_1)` makes it work.
Am i missing some option? Could not find it in the docs.

Thanks in advance!

**Comment by ValentinPromies** [comment]
Hi!

The released binary does not support optimization. While it is possible to compile a strategy that supports optimization for QF_LRA, i do not think that it is supported for QF_LIA at all.
Also note: we are currently not actively researching integer theories or optimization, and thus we do not work on that part of the code.

If you are interested in using SMT-RAT for NRA, we are happy to help.
But if you are only interested in optimization (or integer theories), then other tools are better suited.
