### ISSUE TITLE
floating point exception during execution

### ISSUE THREAD

**Issue by leokarti** [ths-rwth/smtrat#39]
Hi I am using the latest version of smtrat in Debian system and whenever I try to  execute smtrat I get the error "Floating point exception" the input file works with yices and is non-relational algebra (QF_NRA). I have included the input file. and would be really thankful for any [help.](url
[66.zip](https://github.com/smtrat/smtrat/files/3911891/66.zip)

)

**Comment by nafur** [comment]
Unfortunately, division is rather weird in QF_NRA and has already sparked quite some discussion in the community. While the SMTLIB specification (http://smtlib.cs.uiowa.edu/theories-Reals.shtml) states that division by zero is unspecified, but now undefined behaviour. Unfortunately, this specification goes against most arithmetic implementations where division by zero yields exceptions/undefined behaviour/...
In my view, there is no "easy way out", except for considering this weird special case all over the place. In particular, transforming every `(/ x y)` to `z` with `(= (* y z) x)` does not satisfy the specification as it (implicitly) enforces that `y` is not zero (although I would argue that this most likely matches the user's intention). Do you happen to know how yices handles this case?

We thus simply assume that division is always done only using non-zero constants, which is not the case in your example. Most likely, you are seeing GMP divisions fail at https://github.com/smtrat/carl/blob/master/src/carl/core/MultivariatePolynomial.tpp#L275, or rather at https://github.com/smtrat/carl/blob/master/src/carl/core/MultivariatePolynomial.tpp#L1157.

**Comment by leokarti** [comment]
hi nafur, can you please elaborate?
do I need to add an extra library?

**Comment by nafur** [comment]
If you want to SMT-RAT, please reformulate your problems such that you only divide by constants. All other divisions should be reformulated like this: `(/ x y)` to `(= (* y z) x)` with a new real variable `z`.

Above I tried to explain **why** SMT-RAT does not support division (by other terms than constants) right now.

**Comment by leokarti** [comment]
hi nafur , thank you for the fast reply are there any solvers that accept this kind of division other than z3 and yices?

**Comment by nafur** [comment]
Given that the number of SMT solvers that support non-linear arithmetic at all is rather limited: not that many. To the best of my knowledge, apart from z3, yices and SMT-RAT (with complete approaches) there are only MathSAT and CVC4 (implementing linearization approaches) and some ICP-based solvers (raSAT, dReal, iSAT).

I'd really advise you to think about what division means for you (in particular: can the divisor be zero?) and reformulate accordingly. Even though yices gives you a result that is compatible with the SMT-LIB specification, it may very well not be the result you expect.

**Comment by rpgoldman** [comment]
@nafur Is there any chance that SMT-RAT could be enhanced to trap such errors and raise a more helpful error message?

You give a good explanation for why SMT-RAT does not handle division, but the user might not know this, so trapping this when reading the input file would be a big help to users.

**Comment by nafur** [comment]
@derjasper :-)

**Comment by derjasper** [comment]
SMT-RAT will output an error message if the divisor is zero or non-constant in the next release.

**Comment by rpgoldman** [comment]
@derjasper Thank you so much! This will be a great enhancement.
