### ISSUE TITLE
can build, but cannot install smtrat (CArL-EP-doxygen build step failure)

### ISSUE THREAD

**Issue by maychiew1988** [ths-rwth/smtrat#96]
Hello, I am a brand new user of SMT-RAT. :smiley_cat: 

After a "simple" configuration, following the instructions, "make smtrat-shared" succeeds.

```
[100%] Built target smtrat-shared
```

If I then try `make install`, however, it fails:

```
[  9%] Built target CArL-EP
[ 10%] Performing build step for 'CArL-EP-doxygen'
gmake[3]: *** No rule to make target 'doxygen-build'.  Stop.
make[2]: *** [CMakeFiles/CArL-EP-doxygen.dir/build.make:130: resources/src/CArL-EP-doxygen-stamp/CArL-EP-doxygen-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:1771: CMakeFiles/CArL-EP-doxygen.dir/all] Error 2
make: *** [Makefile:182: all] Error 2
```

Attempting to disable all the "build documentation" options in the main smtrat ccmake dialog doesn't chang this. I do have doxygen installed.

Is there some way I can disable the building of CArL documentation, or install the smtrat-shared libraries (and headers) that I think I have been able to build?

This is on a Linux system, and I get the same result using both the current git HEAD as well as the 21.11 tag.

**Comment by derjasper** [comment]
We will have a look on the install target. Note that the smtrat-shared target creates the smtrat-shared binary which can already be executed.

**Comment by maychiew1988** [comment]
Thanks :smile_cat:  You are right, smtrat-shared exists and appears to work - is there a similar workaround to use the various headers and library files without performing the `make install` step?

**Comment by derjasper** [comment]
Unfortunately, I do not have detailed instructions; you may need to set up the build steps manually (i.e. include as external project)

**Comment by derjasper** [comment]
Doxygen is no longer built as an external project, needs to be installed by the package manager if documentation needs to be built.
